# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/kendrick',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/kendrick',
                'lib_path': 'kendrick'},
  'syms': {'kendrick.core': {'kendrick.core.foo': ('core.html#foo', 'kendrick/core.py')}}}
