# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/kendrick',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/kendrick',
                'lib_path': 'kendrick'},
  'syms': { 'kendrick.core': {'kendrick.core.foo': ('core.html#foo', 'kendrick/core.py')},
            'kendrick.explore': { 'kendrick.explore.get_time_averaged_centroids': ( '10_Interactive-plotting/exploring.html#get_time_averaged_centroids',
                                                                                    'kendrick/explore.py'),
                                  'kendrick.explore.histogram': ('10_Interactive-plotting/exploring.html#histogram', 'kendrick/explore.py'),
                                  'kendrick.explore.interactive_plot': ( '10_Interactive-plotting/exploring.html#interactive_plot',
                                                                         'kendrick/explore.py'),
                                  'kendrick.explore.read_mzml': ( '10_Interactive-plotting/exploring.html#read_mzml',
                                                                  'kendrick/explore.py')}}}
