"""Can't wait to make our first Kendrick plot!"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/08_plotting-kendrick-plots.ipynb.

# %% auto #0
__all__ = ['compute_kendrick_mass_and_defect']

# %% ../notebooks/08_plotting-kendrick-plots.ipynb #4f3cc8e4-af36-4843-9d45-7b1555f450b7
from . import read_raw, centralize 
from molmass import Formula 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

# %% ../notebooks/08_plotting-kendrick-plots.ipynb #db0eb0dc-b507-43ec-ac83-e2de2daed2a7
def compute_kendrick_mass_and_defect(mz, monomer='CH2', offset=0.6): 
    '''Compute Kendrick precise mass for array `mz`. 
    
    Default `monomer` is 'CH2'. 
    
    It is not clear to me why the offset by Wim is chosen 0.6. 
    
    Reurns: km, kmd 
    ''' 

    # kendrick precise mass 
    mono_mass = Formula(monomer).monoisotopic_mass 
    km = mz * round(mono_mass) / mono_mass 

    # kendrick nominal mass 
    knm = (km + offset).astype(int)

    # kendrick mass defect
    kmd = knm - km 
    
    return km, kmd

    
