project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right: 
      - icon: github
        href: "https://github.com/fligt/kendrick"
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Theory
        contents: theory/*
      - section: Conversion
        contents: conversion/*

metadata-files: [nbdev.yml]
